package formelements;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;

public class registrationform {

	public static void main(String[] args) throws InterruptedException, AWTException {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\Admin\\Downloads\\selenium\\chromedriver_win32\\chromedriver.exe");
    	WebDriver driver = new ChromeDriver();
    	ChromeOptions op = new ChromeOptions();
    	op.addArguments("--disable--Notifications");
    	driver.get("https://www.foundit.in/seeker/registration");
    	driver.manage().window().maximize();
    	driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[1]/div[2]/div/div/div[1]/div/label")).click();
    	Thread.sleep(2000);
    	Robot robot = new Robot();
    	StringSelection filepath=new StringSelection("C:\\Users\\Admin\\Downloads\\sus\\Thamaraiselvan.pdf");
    	Toolkit.getDefaultToolkit().getSystemClipboard().setContents(filepath,null);
    	Thread.sleep(2000);
    	robot.keyPress(KeyEvent.VK_CONTROL);
    	robot.keyPress(KeyEvent.VK_V);
    	robot.keyRelease(KeyEvent.VK_V);
    	robot.keyRelease(KeyEvent.VK_CONTROL);
    	robot.keyPress(KeyEvent.VK_ENTER);
    	robot.keyRelease(KeyEvent.VK_ENTER);
    	Thread.sleep(2000);
    	System.out.println("file upload was Sucessfull");
    	Thread.sleep(2000);
    	driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[2]/div[1]/div/input")).sendKeys("Thamaraiselvan");
        Thread.sleep(2000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[2]/div[2]/div/input")).sendKeys("selvan.84@gmail.com");
        Thread.sleep(2000);
        driver.findElement(By.xpath("//*[@id=\"parent\"]/div[1]/div/input")).sendKeys("Thamrai@123");
        Thread.sleep(2000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[7]/div/div/div/div[1]/i")).click();
        Thread.sleep(5000);
        Actions action = new Actions(driver);
        WebElement eye = driver.findElement(By.xpath("//*[@id=\"child\"]/i"));
        action.moveToElement(eye).build().perform();
        robot.mousePress(InputEvent.BUTTON1_DOWN_MASK);
        Thread.sleep(4000);
        robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
        Thread.sleep(2000);
        Select select = new Select(driver.findElement(By.className("countryCodes")));
        select.selectByValue("91");
        Thread.sleep(2000);
        driver.findElement(By.name("Mobile Number")).sendKeys("9941178814");
        Thread.sleep(2000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[7]/div/div/div/div[1]/i")).click();
        Thread.sleep(3000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[2]/div[6]/div/div[1]/div/div[1]/span")).click();
    	WebElement from = driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[2]/div[6]/div/div[1]/div/div[1]/input"));
    	from.sendKeys("Chennai");
    	Thread.sleep(3000);
    	from.sendKeys(Keys.ARROW_DOWN);
    	from.sendKeys(Keys.ENTER);
        Thread.sleep(2000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[2]/div[7]/div/div/div/div/div/div[2]/span")).click();
        WebElement from1 = driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[2]/div[7]/div/div/div/div/div/div[2]/input"));
        from1.isSelected();
        from1.sendKeys(Keys.ARROW_DOWN);
        Thread.sleep(1000);
        from1.sendKeys(Keys.ARROW_DOWN);
        Thread.sleep(1000);
        from1.sendKeys(Keys.ARROW_DOWN);
        Thread.sleep(1000);
        from1.sendKeys(Keys.ENTER);
        Thread.sleep(3000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[2]/div[7]/div/div[2]/div/div/div/div[2]/span")).click();
        WebElement from2 = driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[2]/div[7]/div/div[2]/div/div/div/div[2]/input"));
        from2.isSelected();
        from2.sendKeys(Keys.ARROW_DOWN);
        Thread.sleep(1000);
        from2.sendKeys(Keys.ARROW_DOWN);
        Thread.sleep(1000);
        from2.sendKeys(Keys.ARROW_DOWN);
        Thread.sleep(1000);
        from2.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[2]/div[8]/div/label[1]/i")).click();
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[3]/div[1]/div[1]/div/div/div[1]/span")).click();
        WebElement skills = driver.findElement(By.id("skillInput"));
        skills.isSelected();
        Thread.sleep(1000);
        skills.sendKeys("Testing");
        skills.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        skills.sendKeys("INSURANCE");
        skills.sendKeys(Keys.ENTER);
        skills.sendKeys(Keys.TAB);
        Thread.sleep(1000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[3]/div[3]/div[1]/div/div[3]/ul/li[1]/span/span")).click();
        driver.findElement(By.name("Salary")).sendKeys("600000");
        Thread.sleep(1000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[3]/div[4]/div[2]/div[1]/div/div[2]/span")).click();
        WebElement industry= driver.findElement(By.id("industryInput"));
        industry.isSelected();
        industry.sendKeys("Insurance");
        industry.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        industry.sendKeys("IT/Computers - Software");
        industry.sendKeys(Keys.ARROW_DOWN);
        industry.sendKeys(Keys.ENTER);
        industry.sendKeys(Keys.TAB);
        Thread.sleep(1000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[3]/div[5]/div[2]/div[1]/div/div[2]/span")).click();
        WebElement function = driver.findElement(By.id("functionInput"));
        function.isSelected();
        function.sendKeys("IT");
        function.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        function.sendKeys("Customer Service/Call Centre/BPO");
        function.sendKeys(Keys.ENTER);
        function.sendKeys(Keys.TAB);
        Thread.sleep(1000);
        driver.findElement(By.xpath("//*[@id=\"registerThemeDefault\"]/div/div[4]/div/div/div/form/div[3]/div[6]/div/div[1]/div/div[3]")).click();
        WebElement role = driver.findElement(By.id("roleInput"));
        role.isSelected();
        role.sendKeys("Quality Assurance Executive");
        role.sendKeys(Keys.ARROW_DOWN);
        role.sendKeys(Keys.ENTER);
        }
}